package com.example.consumo_de_apis.viewmodel

import android.graphics.Color
import androidx.lifecycle.ViewModel
import com.example.consumo_de_apis.R
import com.example.consumo_de_apis.model.Personage
import java.text.SimpleDateFormat
import java.util.Locale

val listCharacters: MutableList<Personage> = mutableListOf()
class ConsumoViewModel: ViewModel() {
    fun getCharacterList(): MutableList<Personage> {
        val formatter = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault())

        listCharacters.add(Personage(1, "Homer Simpson", "Safety Inspector", 39, "Male", formatter.parse("1956-05-12")!!, "Alive", "Homer Jay Simpson (born May 12, 1956) is a man from Springfield and the protagonist of the animated television series The Simpsons. He is a crude, ignorant, and slobbish individual, although he is fundamentally a good person and shows great caring and loyalty to his family, friends and on occasion, to those he barely knows or those he considers his enemies.", R.drawable.homersimpson))
        listCharacters.add(Personage(2, "Marge Simpson", "Unemployed", 39, "Female", null, "Alive", "Marjorie Jacqueline \\\"Marge\\\" Simpson (née Bouvier) (Born March 19) is the homemaker and matriarch of the Simpson family. She is also one of the five main characters in The Simpsons TV series. She and her husband Homer have three children: Bart, Lisa, and Maggie. Marge is the moralistic force in her family and often provides a raspy and grounding voice in the midst of her family's antics by trying to maintain order in the Simpson household. Aside from her duties at home, Marge has flirted briefly with a number of careers ranging from a police officer to an anti-violence activist.", R.drawable.margesimpson))
        listCharacters.add(Personage(3, "Bart Simpson", "Student at Springfield Elementary School", 10, "Male", formatter.parse("1980-02-23")!!, "Alive", "Bartholomew JoJo \\\"Bart\\\" Simpson (February 23, 1979) is the mischievous, rebellious, misunderstood, disruptive and \\\"potentially dangerous\\\" oldest child of the Simpson family in The Simpsons. He is the only son of Homer and Marge Simpson, and the older brother of Lisa and Maggie. He also has been nicknamed \\\"Cosmo\\\", after discovering a comet in \\\"Bart's Comet\\\". Bart has also been on the cover on numerous comics, such as \\\"Critical Hit\\\", \\\"Simpsons Treasure Trove #11\\\", and \\\"Winter Wingding\\\". Bart also has a 100-issue comic series entitled the Simpson Comics Presents Bart Simpson. Bart is loosely based off of Matt Groening (who's the creator of The Simpsons) and his older brother, Mark Groening.", R.drawable.bartsimpson))
        listCharacters.add(Personage(4, "Lisa Simpson", "Student at Springfield Elementary School", 8, "Female", formatter.parse("1982-05-09")!!, "Alive", "Lisa Marie Simpson is the elder daughter and middle child of the Simpson family and one of the two tritagonists (along with Marge,) of The Simpsons. She was named after a train called Lil' Lisa on her parents' 1st anniversary. In \\\"Homer and Lisa Exchange Cross Words\\\", she called herself Lisa Bouvier after estranging herself from her father after he bet against her in a crossword tournament.", R.drawable.lisasimpson))
        listCharacters.add(Personage(5, "Maggie Simpson", "Unknown", 1, "Female", formatter.parse("1990-11-07")!!, "Alive", "Margaret Lenny \\\"Maggie\\\" Simpson is the one-year-old daughter and youngest child of Marge and Homer Simpson, the baby sister to Bart and Lisa Simpson and one of the five main characters of The Simpsons. She is often seen sucking on her pacifier, and when she walks, she usually trips over her clothing and falls on her face. Because she rarely ever talks, Maggie is the least seen and heard in the Simpson family. Maggie is very young, at the infant age of only 1.", R.drawable.maggiesimpson))
        listCharacters.add(Personage(1, "Homer Simpson", "Safety Inspector", 39, "Male", formatter.parse("1956-05-12")!!, "Alive", "Homer Jay Simpson (born May 12, 1956) is a man from Springfield and the protagonist of the animated television series The Simpsons. He is a crude, ignorant, and slobbish individual, although he is fundamentally a good person and shows great caring and loyalty to his family, friends and on occasion, to those he barely knows or those he considers his enemies.", R.drawable.homersimpson))
        listCharacters.add(Personage(2, "Marge Simpson", "Unemployed", 39, "Female", null, "Alive", "Marjorie Jacqueline \\\"Marge\\\" Simpson (née Bouvier) (Born March 19) is the homemaker and matriarch of the Simpson family. She is also one of the five main characters in The Simpsons TV series. She and her husband Homer have three children: Bart, Lisa, and Maggie. Marge is the moralistic force in her family and often provides a raspy and grounding voice in the midst of her family's antics by trying to maintain order in the Simpson household. Aside from her duties at home, Marge has flirted briefly with a number of careers ranging from a police officer to an anti-violence activist.", R.drawable.margesimpson))
        listCharacters.add(Personage(3, "Bart Simpson", "Student at Springfield Elementary School", 10, "Male", formatter.parse("1980-02-23")!!, "Alive", "Bartholomew JoJo \\\"Bart\\\" Simpson (February 23, 1979) is the mischievous, rebellious, misunderstood, disruptive and \\\"potentially dangerous\\\" oldest child of the Simpson family in The Simpsons. He is the only son of Homer and Marge Simpson, and the older brother of Lisa and Maggie. He also has been nicknamed \\\"Cosmo\\\", after discovering a comet in \\\"Bart's Comet\\\". Bart has also been on the cover on numerous comics, such as \\\"Critical Hit\\\", \\\"Simpsons Treasure Trove #11\\\", and \\\"Winter Wingding\\\". Bart also has a 100-issue comic series entitled the Simpson Comics Presents Bart Simpson. Bart is loosely based off of Matt Groening (who's the creator of The Simpsons) and his older brother, Mark Groening.", R.drawable.bartsimpson))
        listCharacters.add(Personage(4, "Lisa Simpson", "Student at Springfield Elementary School", 8, "Female", formatter.parse("1982-05-09")!!, "Alive", "Lisa Marie Simpson is the elder daughter and middle child of the Simpson family and one of the two tritagonists (along with Marge,) of The Simpsons. She was named after a train called Lil' Lisa on her parents' 1st anniversary. In \\\"Homer and Lisa Exchange Cross Words\\\", she called herself Lisa Bouvier after estranging herself from her father after he bet against her in a crossword tournament.", R.drawable.lisasimpson))
        listCharacters.add(Personage(5, "Maggie Simpson", "Unknown", 1, "Female", formatter.parse("1990-11-07")!!, "Alive", "Margaret Lenny \\\"Maggie\\\" Simpson is the one-year-old daughter and youngest child of Marge and Homer Simpson, the baby sister to Bart and Lisa Simpson and one of the five main characters of The Simpsons. She is often seen sucking on her pacifier, and when she walks, she usually trips over her clothing and falls on her face. Because she rarely ever talks, Maggie is the least seen and heard in the Simpson family. Maggie is very young, at the infant age of only 1.", R.drawable.maggiesimpson))
        listCharacters.add(Personage(1, "Homer Simpson", "Safety Inspector", 39, "Male", formatter.parse("1956-05-12")!!, "Alive", "Homer Jay Simpson (born May 12, 1956) is a man from Springfield and the protagonist of the animated television series The Simpsons. He is a crude, ignorant, and slobbish individual, although he is fundamentally a good person and shows great caring and loyalty to his family, friends and on occasion, to those he barely knows or those he considers his enemies.", R.drawable.homersimpson))
        listCharacters.add(Personage(2, "Marge Simpson", "Unemployed", 39, "Female", null, "Alive", "Marjorie Jacqueline \\\"Marge\\\" Simpson (née Bouvier) (Born March 19) is the homemaker and matriarch of the Simpson family. She is also one of the five main characters in The Simpsons TV series. She and her husband Homer have three children: Bart, Lisa, and Maggie. Marge is the moralistic force in her family and often provides a raspy and grounding voice in the midst of her family's antics by trying to maintain order in the Simpson household. Aside from her duties at home, Marge has flirted briefly with a number of careers ranging from a police officer to an anti-violence activist.", R.drawable.margesimpson))
        listCharacters.add(Personage(3, "Bart Simpson", "Student at Springfield Elementary School", 10, "Male", formatter.parse("1980-02-23")!!, "Alive", "Bartholomew JoJo \\\"Bart\\\" Simpson (February 23, 1979) is the mischievous, rebellious, misunderstood, disruptive and \\\"potentially dangerous\\\" oldest child of the Simpson family in The Simpsons. He is the only son of Homer and Marge Simpson, and the older brother of Lisa and Maggie. He also has been nicknamed \\\"Cosmo\\\", after discovering a comet in \\\"Bart's Comet\\\". Bart has also been on the cover on numerous comics, such as \\\"Critical Hit\\\", \\\"Simpsons Treasure Trove #11\\\", and \\\"Winter Wingding\\\". Bart also has a 100-issue comic series entitled the Simpson Comics Presents Bart Simpson. Bart is loosely based off of Matt Groening (who's the creator of The Simpsons) and his older brother, Mark Groening.", R.drawable.bartsimpson))
        listCharacters.add(Personage(4, "Lisa Simpson", "Student at Springfield Elementary School", 8, "Female", formatter.parse("1982-05-09")!!, "Alive", "Lisa Marie Simpson is the elder daughter and middle child of the Simpson family and one of the two tritagonists (along with Marge,) of The Simpsons. She was named after a train called Lil' Lisa on her parents' 1st anniversary. In \\\"Homer and Lisa Exchange Cross Words\\\", she called herself Lisa Bouvier after estranging herself from her father after he bet against her in a crossword tournament.", R.drawable.lisasimpson))
        listCharacters.add(Personage(5, "Maggie Simpson", "Unknown", 1, "Female", formatter.parse("1990-11-07")!!, "Alive", "Margaret Lenny \\\"Maggie\\\" Simpson is the one-year-old daughter and youngest child of Marge and Homer Simpson, the baby sister to Bart and Lisa Simpson and one of the five main characters of The Simpsons. She is often seen sucking on her pacifier, and when she walks, she usually trips over her clothing and falls on her face. Because she rarely ever talks, Maggie is the least seen and heard in the Simpson family. Maggie is very young, at the infant age of only 1.", R.drawable.maggiesimpson))

        return listCharacters
    }

    fun getCharacterById(id: Int): Personage? {
        return getCharacterList().find { it.id == id }
    }

    fun getStatuesAlive(id: Int): Int {
        if (listCharacters.get(id-1).status == "Alive") {
            return Color.GREEN
        }
        return Color.RED
    }
}
